// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/anim-preload.tsx";
import * as $3 from "./routes/anim-wrapper.tsx";
import * as $4 from "./routes/anim.tsx";
import * as $5 from "./routes/api/joke.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/jsdeliver.tsx";
import * as $8 from "./routes/markdown_example.tsx";
import * as $9 from "./routes/search.tsx";
import * as $$0 from "./islands/AnimationWrapper.tsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/anim-preload.tsx": $2,
    "./routes/anim-wrapper.tsx": $3,
    "./routes/anim.tsx": $4,
    "./routes/api/joke.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/jsdeliver.tsx": $7,
    "./routes/markdown_example.tsx": $8,
    "./routes/search.tsx": $9,
  },
  islands: {
    "./islands/AnimationWrapper.tsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
